### ISSUE TITLE
windows下安装出错

### ISSUE THREAD

**Issue by qcymkxyc** [codeif/flask-cos#1]
ERROR: Command errored out with exit status 1:
   command: 'f:\zq\pycharmproject\code-pipeline\venv\scripts\python.exe' 'f:\zq\pycharmproject\code-pipeline\venv\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_b
uild_wheel 'C:\Users\ADMINI~1.SC-\AppData\Local\Temp\tmpr758milj'
       cwd: C:\Users\ADMINI~1.SC-\AppData\Local\Temp\pip-install-a59tdc52\flask-cos
  Complete output (16 lines):
  Traceback (most recent call last):
    File "f:\zq\pycharmproject\code-pipeline\venv\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "f:\zq\pycharmproject\code-pipeline\venv\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "f:\zq\pycharmproject\code-pipeline\venv\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\ADMINI~1.SC-\AppData\Local\Temp\pip-build-env-cejw19tr\overlay\Lib\site-packages\setuptools\build_meta.py", line 150, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "C:\Users\ADMINI~1.SC-\AppData\Local\Temp\pip-build-env-cejw19tr\overlay\Lib\site-packages\setuptools\build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "C:\Users\ADMINI~1.SC-\AppData\Local\Temp\pip-build-env-cejw19tr\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 5, in <module>
      readme = f.read()
  UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 26: illegal multibyte sequence

**Comment by codeif** [comment]
读取README指定了编码， 但是不确定windows下还有别的问题不。
